// Copyright 2017 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Please note that this file is autogenerated by "npm run postversion" script.

import {VersionInfo} from '@api/frontendapi';

export const version: VersionInfo = {
  'dirty': true,
  'raw': 'v1.8.3-122-g9a751add6-dirty',
  'hash': 'g9a751add6',
  'distance': 122,
  'tag': 'v1.8.3',
  'semver': {
    'raw': 'v1.8.3',
    'major': 1,
    'minor': 8,
    'patch': 3,
    'prerelease': [],
    'build': [],
    'version': '1.8.3'
  },
  'suffix': '122-g9a751add6-dirty',
  'semverString': '1.8.3+122.g9a751add6',
  'packageVersion': '2.0.0-alpha0'
};
