// Copyright 2017 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Please note that this file is autogenerated by "npm run postversion" script.

import {VersionInfo} from '@api/root.ui';

// prettier-ignore
export const version: VersionInfo = {
  'dirty': true,
  'raw': 'v3.0.0-alpha0-436-gfdbd55ee4-dirty',
  'hash': 'gfdbd55ee4',
  'distance': 436,
  'tag': 'v3.0.0-alpha0',
  'semver': {
    'options': {
      'includePrerelease': false,
      'loose': false
    },
    'loose': false,
    'raw': 'v3.0.0-alpha0',
    'major': 3,
    'minor': 0,
    'patch': 0,
    'prerelease': [
      'alpha0'
    ],
    'build': [],
    'version': '3.0.0-alpha0'
  },
  'suffix': '436-gfdbd55ee4-dirty',
  'semverString': '3.0.0-alpha0+436.gfdbd55ee4',
  'packageVersion': '2.7.0'
};
