# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sources:
  - name: api
    handler:
      openapi:
        source: ../api/schema/swagger.json
    transforms:
      - replaceField:
          typeDefs: |
            type Map {
              map: ObjMap!
            }
          replacements:
            - from:
                type: persistentvolume_PersistentVolume
                field: capacity
              to:
                type: Map
                field: map
            - from:
                type: persistentvolume_PersistentVolumeDetail
                field: capacity
              to:
                type: Map
                field: map
            - from:
                type: persistentvolumeclaim_PersistentVolumeClaim
                field: capacity
              to:
                type: Map
                field: map
            - from:
                type: persistentvolumeclaim_PersistentVolumeClaimDetail
                field: capacity
              to:
                type: Map
                field: map
            - from:
                type: v1_ResourceRequirements
                field: limits
              to:
                type: Map
                field: map
            - from:
                type: v1_ResourceRequirements
                field: requests
              to:
                type: Map
                field: map
            - from:
                type: v1_VolumeResourceRequirements
                field: limits
              to:
                type: Map
                field: map
            - from:
                type: v1_VolumeResourceRequirements
                field: requests
              to:
                type: Map
                field: map
            - from:
                type: resourcequota_ResourceQuotaDetail
                field: statusList
              to:
                type: Map
                field: map
            - from:
                type: v1_ContainerStatus
                field: allocatedResources
              to:
                type: Map
                field: map
