# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
extends:
  - stylelint-config-standard-scss
  - stylelint-prettier/recommended
plugins:
  - stylelint-order
  - stylelint-prettier
rules:
  alpha-value-notation: number
  no-descending-specificity:
  order/order:
    - dollar-variables
    - type: at-rule
      name: extend
    - type: at-rule
      name: include
    - declarations
    - type: at-rule
      name: include
      hasBlock: true
    - at-rules
    - rules
  order/properties-alphabetical-order: true
  scss/comment-no-empty:
  scss/dollar-variable-colon-space-after:
  selector-pseudo-element-no-unknown:
