name: Bug Report
description: Report a bug encountered while using Kubernetes Dashboard
labels: kind/bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
        If this matter is security related, please disclose it privately via https://kubernetes.io/security.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it (as minimally and precisely as possible)?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Microsoft Edge
        - Firefox
        - Others

  - type: input
    id: dashboardVersion
    attributes:
      label: Kubernetes Dashboard version
    validations:
      required: true

  - type: input
    id: kubernetesVersion
    attributes:
      label: Kubernetes version
      description: Provide output of 'kubectl version' command.
    validations:
      required: true

  - type: textarea
    id: devEnvironment
    attributes:
      label: Dev environment
      description: |
        Provide outputs of 'go version' and 'node --version' commands.
        It's needed only if you are running Kubernetes Dashboard locally.
