### Application details
APP_NAME := $(PROJECT_NAME)-metrics-scraper
APP_VERSION := v1.0.9
PACKAGE_NAME := k8s.io/$(PROJECT_NAME)/metrics-scraper

### Dirs and paths
METRICS_SCRAPER_DIST_DIRECTORY = $(DIST_DIRECTORY)/dist
METRICS_SCRAPER_DIST_BINARY = $(API_DIST_DIRECTORY)/$(APP_NAME)
METRICS_SCRAPER_TMP_DIRECTORY = $(METRICS_SCRAPER_DIRECTORY)/.tmp
COVERAGE_FILE = $(METRICS_SCRAPER_TMP_DIRECTORY)/coverage.out

