### Application details
APP_NAME := $(PROJECT_NAME)-metrics-scraper
PACKAGE_NAME := k8s.io/$(PROJECT_NAME)/metrics-scraper

### Dirs and paths
METRICS_SCRAPER_DIST_DIRECTORY = $(METRICS_SCRAPER_DIRECTORY)/.dist
METRICS_SCRAPER_DIST_BINARY = $(METRICS_SCRAPER_DIST_DIRECTORY)/$(APP_NAME)
COVERAGE_FILE = $(TMP_DIRECTORY)/$(APP_NAME).coverage.out

