run:
  timeout: 30m
  issues-exit-code: 1
  tests: true
linters:
  disable-all: true
  enable:
    - deadcode
    - gocyclo
    - goimports
    - govet
    - ineffassign
    - misspell
    - structcheck
    - unused
