// Copyright 2017 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Please note that this file is autogenerated by "npm run postversion" script.

import {VersionInfo} from '@api/frontendapi';

// prettier-ignore
export const version: VersionInfo = {
  'dirty': true,
  'raw': 'v2.1.0-34-g542fd956e-dirty',
  'hash': 'g542fd956e',
  'distance': 34,
  'tag': 'v2.1.0',
  'semver': {
    'options': {
      'includePrerelease': false,
      'loose': false
    },
    'loose': false,
    'raw': 'v2.1.0',
    'major': 2,
    'minor': 1,
    'patch': 0,
    'prerelease': [],
    'build': [],
    'version': '2.1.0'
  },
  'suffix': '34-g542fd956e-dirty',
  'semverString': '2.1.0+34.g542fd956e',
  'packageVersion': '3.0.0'
};
