# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Continuous Integration - Helm

on:
  pull_request:
    paths:
    - 'aio/deploy/helm-chart/**'
    - '.github/workflows/ci-helm-workflow.yml'

jobs:
  helm-lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Validate schema
        uses: wiremind/helm-kubeval-action@v1.2.1
        with:
          path: aio/deploy/helm-chart
          config: aio/deploy/helm-chart/config_repos
          version: 1.23.0

      - uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Cleanup charts directory
        id: cleanup
        run: sudo rm -rf aio/deploy/helm-chart/kubernetes-dashboard/charts

      - name: Run chart-testing (lint)
        id: lint
        run: ct lint --config=aio/deploy/helm-chart/.helm-chart-testing.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Install Prometheus Operator CRDs
        id: prom
        run: kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.54.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

      - name: Run chart-testing (install)
        run: ct install --config=aio/deploy/helm-chart/.helm-chart-testing.yaml
