# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI / Metrics scraper
on:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/*.md"
permissions:
  contents: read
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
  TERM: xterm
jobs:
  check:
    name: Static check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/metrics-scraper
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: modules/metrics-scraper/go.mod
          check-latest: true
          cache-dependency-path: modules/metrics-scraper/go.sum

      - name: Install metrics scraper dependencies
        run: go mod download

      - name: Install tools
        working-directory: modules/common/tools
        run: PATH=$PATH:$GOPATH/bin make install

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.52.2
          working-directory: modules/metrics-scraper
          skip-cache: true

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/metrics-scraper
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: modules/metrics-scraper/go.mod
          check-latest: true
          cache-dependency-path: modules/metrics-scraper/go.sum

      - name: Install metrics scraper dependencies
        working-directory: modules/metrics-scraper
        run: go mod download

      - name: Build
        run: PATH=$PATH:$GOPATH/bin make build-cross

  unit:
    name: Run unit tests with coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/metrics-scraper
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: modules/metrics-scraper/go.mod
          check-latest: true
          cache-dependency-path: modules/metrics-scraper/go.sum

      - name: Install metrics scraper dependencies
        run: go mod download

      - name: Test
        run: PATH=$PATH:$GOPATH/bin make coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          name: metrics-scraper-coverage
          files: ./modules/metrics-scraper/coverage.out
          fail_ci_if_error: true
